package com.work.core.model.mapper;

import com.work.core.model.pojo.ItemSourceInfo;
import com.work.core.model.pojo.ItemSourceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ItemSourceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    int countByExample(ItemSourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    int deleteByExample(ItemSourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    @Delete({
        "delete from item_source_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    @Insert({
        "insert into item_source_info (item_id, model_id, ",
        "model_name)",
        "values (#{itemId,jdbcType=INTEGER}, #{modelId,jdbcType=INTEGER}, ",
        "#{modelName,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ItemSourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    int insertSelective(ItemSourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    List<ItemSourceInfo> selectByExample(ItemSourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    @Select({
        "select",
        "id, item_id, model_id, model_name",
        "from item_source_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ItemSourceInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    int updateByExampleSelective(@Param("record") ItemSourceInfo record, @Param("example") ItemSourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    int updateByExample(@Param("record") ItemSourceInfo record, @Param("example") ItemSourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    int updateByPrimaryKeySelective(ItemSourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_source_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    @Update({
        "update item_source_info",
        "set item_id = #{itemId,jdbcType=INTEGER},",
          "model_id = #{modelId,jdbcType=INTEGER},",
          "model_name = #{modelName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ItemSourceInfo record);
}