package com.work.core.model.mapper;

import com.work.core.model.pojo.ModelSourceInfo;
import com.work.core.model.pojo.ModelSourceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ModelSourceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_source_info
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    int countByExample(ModelSourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_source_info
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    int deleteByExample(ModelSourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_source_info
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    @Delete({
        "delete from model_source_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_source_info
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    @Insert({
        "insert into model_source_info (model_id, source_id, ",
        "movie_name, source_name, ",
        "img_path, simple_describe)",
        "values (#{modelId,jdbcType=INTEGER}, #{sourceId,jdbcType=INTEGER}, ",
        "#{movieName,jdbcType=VARCHAR}, #{sourceName,jdbcType=VARCHAR}, ",
        "#{imgPath,jdbcType=VARCHAR}, #{simpleDescribe,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ModelSourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_source_info
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    int insertSelective(ModelSourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_source_info
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    List<ModelSourceInfo> selectByExample(ModelSourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_source_info
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    @Select({
        "select",
        "id, model_id, source_id, movie_name, source_name, img_path, simple_describe",
        "from model_source_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ModelSourceInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_source_info
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    int updateByExampleSelective(@Param("record") ModelSourceInfo record, @Param("example") ModelSourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_source_info
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    int updateByExample(@Param("record") ModelSourceInfo record, @Param("example") ModelSourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_source_info
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    int updateByPrimaryKeySelective(ModelSourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model_source_info
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    @Update({
        "update model_source_info",
        "set model_id = #{modelId,jdbcType=INTEGER},",
          "source_id = #{sourceId,jdbcType=INTEGER},",
          "movie_name = #{movieName,jdbcType=VARCHAR},",
          "source_name = #{sourceName,jdbcType=VARCHAR},",
          "img_path = #{imgPath,jdbcType=VARCHAR},",
          "simple_describe = #{simpleDescribe,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ModelSourceInfo record);
}