package com.work.core.model.mapper;

import com.work.core.model.pojo.MovieSourceClassifyInfo;
import com.work.core.model.pojo.MovieSourceClassifyInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface MovieSourceClassifyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_source_classify_info
     *
     * @mbggenerated Thu May 28 22:57:40 CST 2015
     */
    int countByExample(MovieSourceClassifyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_source_classify_info
     *
     * @mbggenerated Thu May 28 22:57:40 CST 2015
     */
    int deleteByExample(MovieSourceClassifyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_source_classify_info
     *
     * @mbggenerated Thu May 28 22:57:40 CST 2015
     */
    @Delete({
        "delete from movie_source_classify_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_source_classify_info
     *
     * @mbggenerated Thu May 28 22:57:40 CST 2015
     */
    @Insert({
        "insert into movie_source_classify_info (classify_id, source_id)",
        "values (#{classifyId,jdbcType=INTEGER}, #{sourceId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(MovieSourceClassifyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_source_classify_info
     *
     * @mbggenerated Thu May 28 22:57:40 CST 2015
     */
    int insertSelective(MovieSourceClassifyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_source_classify_info
     *
     * @mbggenerated Thu May 28 22:57:40 CST 2015
     */
    List<MovieSourceClassifyInfo> selectByExample(MovieSourceClassifyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_source_classify_info
     *
     * @mbggenerated Thu May 28 22:57:40 CST 2015
     */
    @Select({
        "select",
        "id, classify_id, source_id",
        "from movie_source_classify_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    MovieSourceClassifyInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_source_classify_info
     *
     * @mbggenerated Thu May 28 22:57:40 CST 2015
     */
    int updateByExampleSelective(@Param("record") MovieSourceClassifyInfo record, @Param("example") MovieSourceClassifyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_source_classify_info
     *
     * @mbggenerated Thu May 28 22:57:40 CST 2015
     */
    int updateByExample(@Param("record") MovieSourceClassifyInfo record, @Param("example") MovieSourceClassifyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_source_classify_info
     *
     * @mbggenerated Thu May 28 22:57:40 CST 2015
     */
    int updateByPrimaryKeySelective(MovieSourceClassifyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_source_classify_info
     *
     * @mbggenerated Thu May 28 22:57:40 CST 2015
     */
    @Update({
        "update movie_source_classify_info",
        "set classify_id = #{classifyId,jdbcType=INTEGER},",
          "source_id = #{sourceId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MovieSourceClassifyInfo record);
}