package com.work.core.model.mapper;

import com.work.core.model.pojo.MovieClassify;
import com.work.core.model.pojo.MovieClassifyExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface MovieClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_classify
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    int countByExample(MovieClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_classify
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    int deleteByExample(MovieClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_classify
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    @Delete({
        "delete from movie_classify",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_classify
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    @Insert({
        "insert into movie_classify (classify_name)",
        "values (#{classifyName,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(MovieClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_classify
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    int insertSelective(MovieClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_classify
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    List<MovieClassify> selectByExample(MovieClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_classify
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    @Select({
        "select",
        "id, classify_name",
        "from movie_classify",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    MovieClassify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_classify
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    int updateByExampleSelective(@Param("record") MovieClassify record, @Param("example") MovieClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_classify
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    int updateByExample(@Param("record") MovieClassify record, @Param("example") MovieClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_classify
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    int updateByPrimaryKeySelective(MovieClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_classify
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    @Update({
        "update movie_classify",
        "set classify_name = #{classifyName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MovieClassify record);
}