package com.work.core.model.mapper;

import com.work.core.model.pojo.MovieImgInfo;
import com.work.core.model.pojo.MovieImgInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface MovieImgInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_img_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    int countByExample(MovieImgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_img_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    int deleteByExample(MovieImgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_img_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    @Insert({
        "insert into movie_img_info (source_id, img_path)",
        "values (#{sourceId,jdbcType=INTEGER}, #{imgPath,jdbcType=VARCHAR})"
    })
    int insert(MovieImgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_img_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    int insertSelective(MovieImgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_img_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    List<MovieImgInfo> selectByExample(MovieImgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_img_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    int updateByExampleSelective(@Param("record") MovieImgInfo record, @Param("example") MovieImgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_img_info
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    int updateByExample(@Param("record") MovieImgInfo record, @Param("example") MovieImgInfoExample example);
}