package com.work.core.model.pojo;

import com.util.BasePojo;

public class ItemSourceInfo extends BasePojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_source_info.id
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_source_info.item_id
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_source_info.model_id
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_source_info.model_name
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    private String modelName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_source_info.id
     *
     * @return the value of item_source_info.id
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_source_info.id
     *
     * @param id the value for item_source_info.id
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_source_info.item_id
     *
     * @return the value of item_source_info.item_id
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_source_info.item_id
     *
     * @param itemId the value for item_source_info.item_id
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_source_info.model_id
     *
     * @return the value of item_source_info.model_id
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_source_info.model_id
     *
     * @param modelId the value for item_source_info.model_id
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_source_info.model_name
     *
     * @return the value of item_source_info.model_name
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_source_info.model_name
     *
     * @param modelName the value for item_source_info.model_name
     *
     * @mbggenerated Sun May 10 10:58:39 CST 2015
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }
}