package com.work.core.model.pojo;

import com.util.BasePojo;

public class ModelSourceInfo extends BasePojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_source_info.id
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_source_info.model_id
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_source_info.source_id
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    private Integer sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_source_info.movie_name
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    private String movieName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_source_info.source_name
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    private String sourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_source_info.img_path
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    private String imgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model_source_info.simple_describe
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    private String simpleDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_source_info.id
     *
     * @return the value of model_source_info.id
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_source_info.id
     *
     * @param id the value for model_source_info.id
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_source_info.model_id
     *
     * @return the value of model_source_info.model_id
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_source_info.model_id
     *
     * @param modelId the value for model_source_info.model_id
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_source_info.source_id
     *
     * @return the value of model_source_info.source_id
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_source_info.source_id
     *
     * @param sourceId the value for model_source_info.source_id
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_source_info.movie_name
     *
     * @return the value of model_source_info.movie_name
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public String getMovieName() {
        return movieName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_source_info.movie_name
     *
     * @param movieName the value for model_source_info.movie_name
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public void setMovieName(String movieName) {
        this.movieName = movieName == null ? null : movieName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_source_info.source_name
     *
     * @return the value of model_source_info.source_name
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_source_info.source_name
     *
     * @param sourceName the value for model_source_info.source_name
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_source_info.img_path
     *
     * @return the value of model_source_info.img_path
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_source_info.img_path
     *
     * @param imgPath the value for model_source_info.img_path
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model_source_info.simple_describe
     *
     * @return the value of model_source_info.simple_describe
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public String getSimpleDescribe() {
        return simpleDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model_source_info.simple_describe
     *
     * @param simpleDescribe the value for model_source_info.simple_describe
     *
     * @mbggenerated Thu May 21 15:54:55 CST 2015
     */
    public void setSimpleDescribe(String simpleDescribe) {
        this.simpleDescribe = simpleDescribe == null ? null : simpleDescribe.trim();
    }
}