package com.work.core.model.pojo;

import com.util.BasePojo;

public class MovieSourceDetailInfo extends BasePojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_source_detail_info.id
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_source_detail_info.cover_img_path
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    private String coverImgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_source_detail_info.media_path
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    private String mediaPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_source_detail_info.is_media
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    private Integer isMedia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_source_detail_info.movie_name
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    private String movieName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_source_detail_info.movie_english_name
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    private String movieEnglishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_source_detail_info.movie_time
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    private Integer movieTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_source_detail_info.movie_produce_year
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    private Integer movieProduceYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_source_detail_info.movie_attribute
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    private Integer movieAttribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_source_detail_info.movie_actor
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    private String movieActor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_source_detail_info.movie_direct
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    private String movieDirect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_source_detail_info.movie_country
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    private String movieCountry;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_source_detail_info.id
     *
     * @return the value of movie_source_detail_info.id
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_source_detail_info.id
     *
     * @param id the value for movie_source_detail_info.id
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_source_detail_info.cover_img_path
     *
     * @return the value of movie_source_detail_info.cover_img_path
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public String getCoverImgPath() {
        return coverImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_source_detail_info.cover_img_path
     *
     * @param coverImgPath the value for movie_source_detail_info.cover_img_path
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public void setCoverImgPath(String coverImgPath) {
        this.coverImgPath = coverImgPath == null ? null : coverImgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_source_detail_info.media_path
     *
     * @return the value of movie_source_detail_info.media_path
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public String getMediaPath() {
        return mediaPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_source_detail_info.media_path
     *
     * @param mediaPath the value for movie_source_detail_info.media_path
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public void setMediaPath(String mediaPath) {
        this.mediaPath = mediaPath == null ? null : mediaPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_source_detail_info.is_media
     *
     * @return the value of movie_source_detail_info.is_media
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public Integer getIsMedia() {
        return isMedia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_source_detail_info.is_media
     *
     * @param isMedia the value for movie_source_detail_info.is_media
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public void setIsMedia(Integer isMedia) {
        this.isMedia = isMedia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_source_detail_info.movie_name
     *
     * @return the value of movie_source_detail_info.movie_name
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public String getMovieName() {
        return movieName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_source_detail_info.movie_name
     *
     * @param movieName the value for movie_source_detail_info.movie_name
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public void setMovieName(String movieName) {
        this.movieName = movieName == null ? null : movieName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_source_detail_info.movie_english_name
     *
     * @return the value of movie_source_detail_info.movie_english_name
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public String getMovieEnglishName() {
        return movieEnglishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_source_detail_info.movie_english_name
     *
     * @param movieEnglishName the value for movie_source_detail_info.movie_english_name
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public void setMovieEnglishName(String movieEnglishName) {
        this.movieEnglishName = movieEnglishName == null ? null : movieEnglishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_source_detail_info.movie_time
     *
     * @return the value of movie_source_detail_info.movie_time
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public Integer getMovieTime() {
        return movieTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_source_detail_info.movie_time
     *
     * @param movieTime the value for movie_source_detail_info.movie_time
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public void setMovieTime(Integer movieTime) {
        this.movieTime = movieTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_source_detail_info.movie_produce_year
     *
     * @return the value of movie_source_detail_info.movie_produce_year
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public Integer getMovieProduceYear() {
        return movieProduceYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_source_detail_info.movie_produce_year
     *
     * @param movieProduceYear the value for movie_source_detail_info.movie_produce_year
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public void setMovieProduceYear(Integer movieProduceYear) {
        this.movieProduceYear = movieProduceYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_source_detail_info.movie_attribute
     *
     * @return the value of movie_source_detail_info.movie_attribute
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public Integer getMovieAttribute() {
        return movieAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_source_detail_info.movie_attribute
     *
     * @param movieAttribute the value for movie_source_detail_info.movie_attribute
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public void setMovieAttribute(Integer movieAttribute) {
        this.movieAttribute = movieAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_source_detail_info.movie_actor
     *
     * @return the value of movie_source_detail_info.movie_actor
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public String getMovieActor() {
        return movieActor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_source_detail_info.movie_actor
     *
     * @param movieActor the value for movie_source_detail_info.movie_actor
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public void setMovieActor(String movieActor) {
        this.movieActor = movieActor == null ? null : movieActor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_source_detail_info.movie_direct
     *
     * @return the value of movie_source_detail_info.movie_direct
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public String getMovieDirect() {
        return movieDirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_source_detail_info.movie_direct
     *
     * @param movieDirect the value for movie_source_detail_info.movie_direct
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public void setMovieDirect(String movieDirect) {
        this.movieDirect = movieDirect == null ? null : movieDirect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_source_detail_info.movie_country
     *
     * @return the value of movie_source_detail_info.movie_country
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public String getMovieCountry() {
        return movieCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_source_detail_info.movie_country
     *
     * @param movieCountry the value for movie_source_detail_info.movie_country
     *
     * @mbggenerated Sun Jun 07 22:02:19 CST 2015
     */
    public void setMovieCountry(String movieCountry) {
        this.movieCountry = movieCountry == null ? null : movieCountry.trim();
    }
}