package com.work.core.model.pojo;

import com.util.BasePojo;

public class MovieClassify extends BasePojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_classify.id
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_classify.classify_name
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    private String classifyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_classify.id
     *
     * @return the value of movie_classify.id
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_classify.id
     *
     * @param id the value for movie_classify.id
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_classify.classify_name
     *
     * @return the value of movie_classify.classify_name
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    public String getClassifyName() {
        return classifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_classify.classify_name
     *
     * @param classifyName the value for movie_classify.classify_name
     *
     * @mbggenerated Sat May 16 22:10:50 CST 2015
     */
    public void setClassifyName(String classifyName) {
        this.classifyName = classifyName == null ? null : classifyName.trim();
    }
}